namespace TK.Audio
{
    public enum SFXId
    {
        Grab,
        EatFood,
        EatTrash,
        Rating,
        ButtonClick,
        PanelOpen,
        PanelClose,
        PageTurn,
        Burp,
        Growl,
        Fall,
        Land,
        Rise,
        PutHand,
        Take,
        Release,
        CantRelease,
        Digging,
        Horn,
        Point,
        TextTalk,
        TextScream,
        Boing,
        Explosion,
        Expand
    }
}
